// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNbNNs3gQT4vIvsPbnrG7ljT4srlrp_K0',
    appId: '1:57964001900:web:0639c273c7d3b046c0b649',
    messagingSenderId: '57964001900',
    projectId: 'my-bot-d9d21',
    authDomain: 'my-bot-d9d21.firebaseapp.com',
    storageBucket: 'my-bot-d9d21.firebasestorage.app',
    measurementId: 'G-KEHB6FKYCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5VlqQfWb9_EyPYMzI6ZakExqpyoHQdgg',
    appId: '1:57964001900:android:e776b83df979b07dc0b649',
    messagingSenderId: '57964001900',
    projectId: 'my-bot-d9d21',
    storageBucket: 'my-bot-d9d21.firebasestorage.app',
  );
}
